[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "http://api.open-notify.org/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"